### ISSUE TITLE
Bintray API key exposed

### ISSUE THREAD

**Issue by gsauthof** [emccode/dvdcli#16]
It looks like your are publishing your Bintray API key unencrypted in `.bintray-decapitate.sh`:

```
BINTRAY_USER=clintonskitson
BINTRAY_APIKEY=2909ff03d795fd4d824d787e9d96142c0cb6d110
BINTRAY_ACCOUNT=emccode
BINTRAY_REPO=dvdcli
BINTRAY_URL=https://api.bintray.com/content/$BINTRAY_ACCOUNT/$BINTRAY_REPO
```

Usually, the API key for a service like Bintray is considered secret.

For example, travis ci provides features for dealing with this (e.g. encrypted environment variables and repository variables).

You probably want to revoke that key and change this script. And audit your published binaries.

**Comment by akutz** [comment]
@gsauthof,

Thanks for the info! This is my fault -- @clintonskitson copied my original work. I've since updated my scripts, such as [`.bintray-decapitate.sh`](https://github.com/emccode/rexray/blob/master/.build/bintray-decapitate.sh), so @clintonskitson should just copy them over and use environment variables.

**Comment by clintkitson** [comment]
Thanks @gsauthof the API key has been revoked. @dvonthenen Can you look at this?
