### ISSUE TITLE
dvdcli create volume when mount if the volume does not exist

### ISSUE THREAD

**Issue by gyliu513** [emccode/dvdcli#18]
The current behavior of dvdcli for mount and unmount is that if the volume does not exist, the dvdcli will help create the volume first, it is better add an option to enable end user to decide if want to create the volume or not.

I also asked the same question in docker community and they said that this is not a good behaviour https://github.com/docker/docker/issues/21829 , the volume created by default may not fit to customer workload well.

**Comment by gyliu513** [comment]
@clintonskitson can you help?

**Comment by clintkitson** [comment]
The feature is there because it aligns with consuming volumes that are
local. I believe this kind of a change is a bigger design update that would
occur with volumes in Docker.

This can be behavior that is changed by dvdcli since we have the
opportunity to request information about volumes before proceeding with a
mount command.

To get there we need to update the dvdcli tool to align to the Docker 1.10
volume API which brings the Get() method.

It could be a parameter that gets added to the module configuration that
determines that the pre check happen before mounts occur.

**Comment by gyliu513** [comment]
Thanks @clintonskitson I have some difficulty in building the dvdcli locally, seems got some dependency issue, I'm planning to generate a pull request, can you please help check and merge? Thanks.

**Comment by gyliu513** [comment]
@clintonskitson I created a pull request: https://github.com/emccode/dvdcli/pull/19

But I have some problem to compile in my local environment, can you please help check if my code is OK? This is requested by https://issues.apache.org/jira/browse/MESOS-4355 and I was working on the mesos patches, hope can get some help from you, thanks again for your support!

```
root@ma1demo3:~/gyliu/dvdcli# make
SemVer: 0.1.1-dev+8
RpmVer: 0.1.1+dev+8
Branch: master
Commit: 3c3dcbe1490c2c4a150555978f2b4915dafaddf2
Formed: Wed, 13 Apr 2016 00:26:56 EDT

target: deps
  ...installing glide...SUCCESS!
  ...downloading go dependencies...make: *** [_deps] Error 1
target: fmt
  ...formatting dvdcli...SUCCESS!
make: Target `all' not remade because of errors.
```

**Comment by clintkitson** [comment]
Check this PR https://github.com/emccode/dvdcli/pull/20

**Comment by clintkitson** [comment]
@jay-lau Can you close this if satisfied with https://github.com/emccode/dvdcli/releases/tag/v0.2.0 ?

**Comment by gyliu513** [comment]
Cool, glad to see that we have 0.2.0 released!
